name: "Filebeat"
description: "Send Home Assistant journal logs to Elasticsearch through Filebeat"
version: "1.0.9"
slug: "filebeat"
arch:
  - aarch64
  - amd64
init: false
journald: true
startup: "application"
map:
  - config
options:
  elasticsearch_hosts: "elasticsearch:9200"
schema:
  elasticsearch_hosts: "str"
  elasticsearch_username: "str?"
  elasticsearch_password: "password?"
